sudo: false
dist: xenial
language: php

services:
  - mysql

php:
  - 7.4
  - 7.3
  - 7.2
  - 7.1
env:
  - OMNIPAY_VERSION=~2.0
  - OMNIPAY_VERSION=~3.0

matrix:
  fast_finish: true

before_script:
  - git clone --depth=50 --branch=2020.04 git://github.com/aimeos/aimeos-core.git ../aimeos-core
  - cd ../aimeos-core && mv ../ai-payments ext/
  - travis_retry composer require "php-http/guzzle6-adapter" "omnipay/common:${OMNIPAY_VERSION}" "academe/omnipay-datatrans:${OMNIPAY_VERSION}" "omnipay/dummy:${OMNIPAY_VERSION}" "academe/omnipay-payone:${OMNIPAY_VERSION}" "omnipay/stripe:${OMNIPAY_VERSION}"
  - mysql -e "CREATE DATABASE aimeos; GRANT ALL ON aimeos.* TO 'aimeos'@'127.0.0.1' IDENTIFIED BY 'aimeos'"
  - echo "<?php return array( 'db' => array( 'adapter' => 'mysql', 'host' => '127.0.0.1', 'database' => 'aimeos', 'username' => 'aimeos', 'password' => 'aimeos', 'limit' => 2, 'opt-persistent' => false, 'stmt' => array( \"SET SESSIOn sort_buffer_size=2097144; SET NAMES 'utf8'; SET SESSION sql_mode='ANSI'\" ) ), 'mq' => array( 'adapter' => 'Standard', 'db' => 'db' ) );" > config/resource.php

script:
  - vendor/bin/phing -Ddir=ext/ai-payments setup coverageext checkext

after_success:
  - php vendor/bin/coveralls -c ext/ai-payments/.coveralls.yml
